name: NPM Deprecate PR versions On Merge

on:
  pull_request:
    types:
      - closed

jobs:
  deprecate-on-merge:
    name: NPM Deprecate PR versions On Merge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Use Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          registry-url: https://registry.npmjs.org/

      - name: Install Dependencies
        run: pnpm install --prefer-frozen-lockfile

      - name: Deprecate PR versions
        run: pnpm npm-deprecate --name "*pr-${{ github.event.number }}*" -d -v
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
