name: Publish

on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    if: github.repository_owner == 'swiizyy'
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.0
          run_install: true

      - name: Configure Git
        run: |
          git remote set-url origin "https://${GITHUB_TOKEN}:x-oauth-basic@github.com/${GITHUB_REPOSITORY}.git"
          git config --local user.email "${GITHUB_EMAIL}"
          git config --local user.name "${GITHUB_USER}"
        env:
          GITHUB_USER: github-actions[bot]
          GITHUB_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: pnpm build

      - name: Bump Versions and make release
        run: |
          pnpm bump ${inputs.skip-automatic-bump ? '--skip-automatic-bump' : ''}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to NPM
        run: |
          pnpm config set npmAuthToken ${NODE_AUTH_TOKEN}
          pnpm config set npmPublishRegistry "https://registry.npmjs.org"
          pnpm npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
